version: "3.9"

services:

    django:
        build:
            context: .
            dockerfile: ./docker/local/django/Dockerfile
        volumes:
            - .:/app:z
            - static_volume:/app/staticfiles
            - media_volume:/app/mediafiles
        expose:
            - "8000"
        env_file:
            - ./.envs/.local/.django
            - ./.envs/.local/.postgres
        depends_on:
            - postgres
            - mailhog
        command: /start
        networks:
            - blog-api

    postgres:
        build:
            context: .
            dockerfile: ./docker/local/postgres/Dockerfile
        volumes:
            - local_postgres_data:/var/lib/postgresql/data
            - local_postgres_data_backups:/backups
        env_file:
            - ./.envs/.local/.postgres
        networks:
            - blog-api

    nginx:
        restart: always
        build:
            context: ./docker/local/nginx/
            dockerfile: Dockerfile
        volumes:
            - static_volume:/app/staticfiles
            - media_volume:/app/mediafiles
        ports:
            - "8080:80"
        depends_on:
            - django
        networks:
            - blog-api

    mailhog:
        image: mailhog/mailhog:v1.0.0
        container_name: mailhog
        ports:
            - "8025:8025"
        networks:
            - blog-api

networks:
    blog-api:
        driver: bridge

volumes:
    static_volume:
    media_volume:
    local_postgres_data: {}
    local_postgres_data_backups: {}