#!/bin/bash

set -o errexit
set -o nounset

# TODO: Change -A with your django project name
exec watchfiles celery.__main__.main \
    --args \
    "-A blog_api.celery -b \"${CELERY_BROKER}\" flower --basic_auth=\"${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}\""