# Generated by Django 4.1.7 on 2023-09-20 18:16

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=50,
                unique=True,
                validators=[apps.users.models.validate_username],
                verbose_name="username",
            ),
        ),
    ]
